name: Fetch Codewars Solutions

on:
  schedule:
    - cron: '0 14 * * *'
  push:
    branches:
      - main

jobs:
  fetch_solutions:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Execute Script
        run: ruby fetch_solutions.rb

      - name: Commit Changes
        run: |
          git config --global user.name "Bimai6"
          git config --global user.email "bimaivfx@gmail.com"
          git add .
          git commit -m "Auto: New solutions from Codewars" || echo "Nothing new to add"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Bimai6/codewars-solutions.git HEAD:main
